"""Build the DOOM unity file and compile it with BMO C.

BMO C has no linker: everything a program calls has to be in the same
translation unit. So the way DOOM gets compiled here is the way SQLite ships
itself -- one file that includes all the others.

That is also what makes the remaining per-file failures disappear: nine of them
are a symbol defined in ANOTHER file, and in a unity build there is no other
file.

Usage:  python unity.py          builds and compiles
        python unity.py --keep   also leaves bmo_unity.c to read
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = r"C:\Users\Salazar\Documents\BMO"
CFRONT = os.path.join(REPO, "target", "release", "bmo-c-front.exe")
DOOM = os.path.join(os.path.dirname(HERE), "doom", "doomgeneric", "doomgeneric")
INCLUDE = os.path.join(HERE, "include")
OUT = os.path.join(HERE, "out")

# The platform backends the port replaces, and the sound ones that pull SDL in.
SKIP_PREFIX = ("doomgeneric_", "bmo_")
SKIP = {"i_allegromusic.c", "i_allegrosound.c", "i_sdlmusic.c", "i_sdlsound.c",
        "icon.c", "i_cdmus.c"}

files = sorted(f for f in os.listdir(DOOM)
               if f.endswith(".c") and not f.startswith(SKIP_PREFIX)
               and f not in SKIP)

unity = os.path.join(DOOM, "bmo_unity.c")
with open(unity, "w", encoding="latin-1") as out:
    out.write("/* Generated by doom-port/unity.py -- do not edit. */\n")
    for f in files:
        out.write('#include "%s"\n' % f)

lineas = sum(1 for f in files
             for _ in open(os.path.join(DOOM, f), encoding="latin-1"))
print("unity: %d ficheros, %d lineas de fuente" % (len(files), lineas))

# ** SE COMPILA `doomgeneric_bmo.c`, NO `bmo_unity.c`. (arreglado 2026-09-01)
#
# El de arriba es el AGREGADO -- 81 ficheros de DOOM y ningun `main`, porque el
# punto de entrada vive en la capa de plataforma. Y la capa de plataforma es la
# que INCLUYE al agregado, no al reves:
#
#     doomgeneric_bmo.c  ->  #include "bmo_unity.c"  ->  los 81
#
# Compilando el agregado, el frontend contestaba
#
#     error: no hay funcion 'main': un programa de Ring 3 necesita punto de entrada
#
# ...y este guion lo imprimia como una linea mas y SALIA CON CODIGO 0. O sea que
# parecia que habia construido algo. `out/doom.bex` llevaba desde el 14-08 sin
# tocarse y nadie lo noto, porque el binario que se desplegaba se construia a
# mano con la orden que la cabecera de `doomgeneric_bmo.c` documenta.
#
# > Un guion que falla y sale con 0 no es un guion roto: es un guion que MIENTE.
ENTRADA = os.path.join(DOOM, "doomgeneric_bmo.c")

os.makedirs(OUT, exist_ok=True)
env = dict(os.environ)
env["BMO_MODS"] = INCLUDE
proc = subprocess.run(
    [CFRONT, ENTRADA, "-o", os.path.join(OUT, "doom.bex")],
    capture_output=True, text=True, env=env, cwd=REPO, timeout=1800,
)

salida = (proc.stdout or "") + (proc.stderr or "")
for linea in salida.strip().splitlines()[:12]:
    print("  " + linea[:150])

# ** Y SE DICE QUE ES ESTO Y QUE NO, porque la confusion costo dias.
#
# `out/doom.bex` NO se juega: no esta donde el despliegue mira y **no lleva el
# icono**, que el build le mete con `bmo-pack` despues de compilar (el icono es
# original y se dibuja en `build/ejemplos.ps1` a proposito: una imagen de DOOM
# seria de id Software).
print('')
print('unity: esto es para ITERAR. `out/doom.bex` no lleva icono ni se')
print('       despliega. Para JUGAR:  bmo.ps1  -- compila DOOM directo a')
print('       staging/BMO-DATA/apps/, le pone la cara y lo deja listo.')

# Y el codigo de salida se propaga, que es lo que faltaba.
if proc.returncode != 0:
    sys.exit("unity: NO se construyo doom.bex (codigo %d)" % proc.returncode)

# ** [!] AQUI NO SE DESPLIEGA, Y ES IMPORTANTE. (2026-09-02)
#
# Estuvo diez minutos copiando `out/doom.bex` a `staging/BMO-DATA/apps/`, y
# **estaba mal**: el build del repo ya construye DOOM y lo hace MEJOR.
#
#     Ultra_kernel_x86-64/build/ejemplos.ps1:398
#
# Compila `doomgeneric_bmo.c` DIRECTO a staging --sin pasar por `out/`-- y
# despues **le mete el icono como recurso del paquete**. Por eso su binario pesa
# ~1.159 bytes mas que este, y por eso DOOM tiene cara en el escritorio sin que
# nadie mantenga un `.lnk`.
#
# *** O sea que copiar de aqui a staging no era "desplegar": era **quitarle el
# icono a DOOM** y dejar un binario peor donde habia uno bueno. El fallo de
# fondo es el mismo que ya paso hoy con `cargo test --workspace`: inventarse una
# ruta que el proyecto ya tenia, sin mirar si la tenia.
#
# > Antes de automatizar un paso, buscar si ya esta automatizado.
#
# Este guion sigue valiendo para ITERAR: compila rapido a `out/` sin levantar el
# build entero. Para PROBAR en la maquina, la orden es `.\\bmo.ps1`, que lo
# construye, le pone la cara y lo deja donde toca.

if "--keep" not in sys.argv:
    pass  # el fichero se deja siempre: es lo que se abre con -E
