//! GENERADO POR `toolchain/tools/estratos-guia/guia.py` DESDE EL CONTRATO DEL ABI
//! (`platform/abi/bmo-abi/src/syscalls/surface/`) -- NO EDITAR A MANO.
//!
//! La GUIA de ESTRATOS en F1 (`docs/plan/PLAN_LAS_RAMAS.md`, R1): cada puerta
//! que existe, con QUE hace y POR QUE, copiadas del comentario que la define.
//! Lo que se edita es el contrato; esto lo sigue.

/// Una puerta de ESTRATOS, como la cuenta el contrato.
pub struct Door {
    pub family: usize,
    pub name: &'static str,
    pub door: &'static str,
    pub value: u64,
    pub what: &'static str,
    pub why: &'static str,
}

/// (nombre, que es, escribe?) de cada familia, por su prefijo.
pub static FAMILIES: [(&str, &str, bool); 5] = [
    ("EL CURSOR", "lee: un cursor que baja y sube por el arbol del volumen", false),
    ("LA HISTORIA", "lee: la cadena de versiones, de ahora hacia atras", false),
    ("LOS NOMBRES", "lee: los textos que el cursor y la historia no caben en un numero", false),
    ("LOS GESTOS", "escribe: cada gesto publica un estrato nuevo; nada se pisa", true),
    ("LAS RAMAS", "escribe: crear, cambiar y mezclar en dos fases (contar y elegir solo leen)", true),
];

/// Cuantas puertas hay: la guia lo dice con este numero, no con uno escrito.
pub const COUNT: usize = 45;

/// `static`: UNA copia en `.rodata`, que Ring 3 lee por indice.
pub static DOORS: [Door; COUNT] = [
    Door {
        family: 0,
        name: "raiz",
        door: "ES_NODO_RAIZ",
        value: 0,
        what: "Pone el cursor en la RAIZ del volumen. 0 si no hay volumen montado.",
        why: "Es la primera pregunta de cualquier recorrido: el cursor guarda la ruta desde aqui, y cada nivel por el que se baja se queda con su listado.",
    },
    Door {
        family: 0,
        name: "hijos",
        door: "ES_NODO_HIJOS",
        value: 1,
        what: "Cuantos hijos tiene el nodo donde esta el cursor.",
        why: "",
    },
    Door {
        family: 0,
        name: "truncado",
        door: "ES_NODO_TRUNCADO",
        value: 2,
        what: "1 si el listado NO cabia entero. Se pregunta y se dice: un directorio truncado en silencio se ve igual que uno corto.",
        why: "",
    },
    Door {
        family: 0,
        name: "hondo",
        door: "ES_NODO_HONDO",
        value: 3,
        what: "Cuantos niveles se ha bajado desde la raiz.",
        why: "",
    },
    Door {
        family: 0,
        name: "tipo",
        door: "ES_NODO_TIPO",
        value: 4,
        what: "Tipo del nodo actual: 0 archivo, 1 directorio, 2 no hay nada.",
        why: "",
    },
    Door {
        family: 0,
        name: "hijo tipo",
        door: "ES_NODO_HIJO_TIPO",
        value: 5,
        what: "Tipo del hijo arg1. Mismos codigos que ES_NODO_TIPO.",
        why: "",
    },
    Door {
        family: 0,
        name: "entrar",
        door: "ES_NODO_ENTRAR",
        value: 6,
        what: "Baja al hijo arg1. 1 si se pudo.",
        why: "",
    },
    Door {
        family: 0,
        name: "subir",
        door: "ES_NODO_SUBIR",
        value: 7,
        what: "Vuelve al padre. 1 si se pudo, 0 si ya estaba en la raiz.",
        why: "",
    },
    Door {
        family: 0,
        name: "hijo bytes",
        door: "ES_NODO_HIJO_BYTES",
        value: 8,
        what: "Bytes de su contenido. Un directorio contesta lo que ocupa su lista de entradas -- que tambien es un dato, y distinto de lo que hay dentro.",
        why: "",
    },
    Door {
        family: 0,
        name: "hijo atributos",
        door: "ES_NODO_HIJO_ATRIBUTOS",
        value: 9,
        what: "Cuantos atributos lleva. Es el numero que dice que ESTRATOS no es un sistema de carpetas: un nodo es un conjunto de atributos, y un archivo y un directorio se diferencian en cual llevan, no en su estructura.",
        why: "",
    },
    Door {
        family: 0,
        name: "hijo firmado",
        door: "ES_NODO_HIJO_FIRMADO",
        value: 10,
        what: "1 si lleva :firma. Solo si la lleva, no si cuadra -- comprobarlo exige leer el contenido entero, y eso no puede pasar en cada repintado.",
        why: "",
    },
    Door {
        family: 0,
        name: "verificar",
        door: "ES_NODO_VERIFICAR",
        value: 11,
        what: "Lee el hijo y compara su BLAKE3 con su :firma. Se pide a mano.",
        why: "Demuestra que los bytes son los que se guardaron --caza corrupcion y escrituras a medias--. No demuestra autenticidad: quien pueda escribir en el volumen puede cambiar el archivo y recalcular su hash.",
    },
    Door {
        family: 0,
        name: "nivel hijos",
        door: "ES_NODO_NIVEL_HIJOS",
        value: 12,
        what: "Cuantos hijos tiene el nivel arg1. 0 si ese nivel no existe todavia.",
        why: "",
    },
    Door {
        family: 0,
        name: "nivel hijo tipo",
        door: "ES_NODO_NIVEL_HIJO_TIPO",
        value: 13,
        what: "El tipo del hijo de un nivel: 0 archivo, 1 directorio, 2 no hay.",
        why: "",
    },
    Door {
        family: 0,
        name: "nivel elegido",
        door: "ES_NODO_NIVEL_ELEGIDO",
        value: 14,
        what: "Por que hijo se bajo desde el nivel arg1, o u64::MAX si por ninguno.",
        why: "El valor imposible NO es un capricho: cero es un hijo perfectamente valido --el primero--, asi que \"por ninguno\" no se puede decir con un cero sin que el nivel donde acaba la rama se confunda con uno abierto por su primer hijo.",
    },
    Door {
        family: 0,
        name: "recargar",
        door: "ES_NODO_RECARGAR",
        value: 15,
        what: "Relee el arbol y deja el cursor donde estaba.",
        why: "",
    },
    Door {
        family: 1,
        name: "releer",
        door: "ES_HIST_RELEER",
        value: 16,
        what: "Recorre la cadena y guarda las versiones. Devuelve cuantas se leyeron. Se pide al abrir el panel y despues de escribir.",
        why: "",
    },
    Door {
        family: 1,
        name: "cuantas",
        door: "ES_HIST_CUANTAS",
        value: 17,
        what: "Cuantas versiones hay guardadas.",
        why: "",
    },
    Door {
        family: 1,
        name: "recortada",
        door: "ES_HIST_RECORTADA",
        value: 18,
        what: "Se corto el recorrido por el tope? Una historia recortada en silencio se ve igual que un volumen joven.",
        why: "",
    },
    Door {
        family: 1,
        name: "cuando",
        door: "ES_HIST_CUANDO",
        value: 19,
        what: "Cuando se hizo la version arg1, en el formato de INFO_FECHA. 0 = sin fechar.",
        why: "",
    },
    Door {
        family: 1,
        name: "quien",
        door: "ES_HIST_QUIEN",
        value: 20,
        what: "Que proceso hizo la version arg1.",
        why: "",
    },
    Door {
        family: 1,
        name: "con nombre",
        door: "ES_HIST_CON_NOMBRE",
        value: 21,
        what: "Lleva nombre la version arg1?",
        why: "Las que si son PERMANENTES: el recolector no las suelta jamas. Por eso esto no es un adorno de la lista -- es la diferencia entre una version que puede desaparecer y una a la que siempre se podra volver.",
    },
    Door {
        family: 2,
        name: "hijo",
        door: "ES_TXT_HIJO",
        value: 0,
        what: "El nombre del hijo indice del nodo donde esta el cursor.",
        why: "",
    },
    Door {
        family: 2,
        name: "ruta",
        door: "ES_TXT_RUTA",
        value: 1,
        what: "El nombre del nivel indice de la ruta. 0 es la raiz y contesta vacio.",
        why: "",
    },
    Door {
        family: 2,
        name: "nivel hijo",
        door: "ES_TXT_NIVEL_HIJO",
        value: 2,
        what: "El nombre de un hijo de CUALQUIER nivel, para el panel de arbol.",
        why: "",
    },
    Door {
        family: 2,
        name: "hist nombre",
        door: "ES_TXT_HIST_NOMBRE",
        value: 3,
        what: "El nombre de la version indice de la historia.",
        why: "",
    },
    Door {
        family: 3,
        name: "limpiar",
        door: "ES_GESTO_LIMPIAR",
        value: 0,
        what: "Vacia el renglon del contenido. Se manda ANTES de acumular nada.",
        why: "Existe para que un intento a medias no envenene al siguiente: si un programa muere despues de mandar tres trozos, el renglon se queda con ellos dentro. Empezar limpiando es mas barato que un tiempo de expiracion.",
    },
    Door {
        family: 3,
        name: "datos",
        door: "ES_GESTO_DATOS",
        value: 1,
        what: "Acumula contenido. arg1 son 8 bytes en little-endian, y cuantos de esos ocho valen viaja empaquetado con la suborden: ES_GESTO_DATOS | (n << 8).",
        why: "Se parte arg0 porque por la puerta caben dos argumentos y los dos estan ocupados. Es el mismo idioma que INFO_MEM_QUIEN_ y AUTOPSIA_TEXTO: cuando cabe un numero y hacen falta dos, se parte el numero.",
    },
    Door {
        family: 3,
        name: "fichero",
        door: "ES_GESTO_FICHERO",
        value: 2,
        what: "Cierra la transaccion. El nombre sale del renglon de TASK_OP_RUTA y el contenido del de arriba. Devuelve la generacion nueva, o 0.",
        why: "",
    },
    Door {
        family: 3,
        name: "carpeta",
        door: "ES_GESTO_CARPETA",
        value: 3,
        what: "Crea una carpeta vacia donde diga la ruta.",
        why: "",
    },
    Door {
        family: 3,
        name: "quitar",
        door: "ES_GESTO_QUITAR",
        value: 4,
        what: "Quita la entrada que diga la ruta.",
        why: "No destruye nada. Se publica un arbol nuevo sin esa entrada; el bloque de ayer, el nodo del fichero y el estrato anterior siguen donde estaban. Borrar en ESTRATOS es dejar de nombrar, y lo que se suelta de verdad es cosa del recolector.",
    },
    Door {
        family: 3,
        name: "renombrar",
        door: "ES_GESTO_RENOMBRAR",
        value: 5,
        what: "Renombra la entrada que diga la ruta. El nombre NUEVO viaja por el renglon del contenido (ES_GESTO_DATOS).",
        why: "El nodo NO se toca: la entrada nueva apunta al mismo bloque, asi que el contenido, los atributos y la :firma siguen siendo los de antes. Renombrar un fichero firmado no le invalida la firma.",
    },
    Door {
        family: 3,
        name: "copia",
        door: "ES_GESTO_COPIA",
        value: 6,
        what: "Trae un fichero de FAT32 a ESTRATOS.",
        why: "El contenido NO cruza la puerta. Viajan dos NOMBRES, y el kernel lee la fuente el mismo: meter un fichero por el renglon de ocho en ocho serian 512 llamadas por bloque, y ese renglon no esta hecho para eso.",
    },
    Door {
        family: 3,
        name: "marcar",
        door: "ES_GESTO_MARCAR",
        value: 7,
        what: "Marca la version en curso con un nombre, que viaja por el renglon de la ruta.",
        why: "Un nombre no describe una version: la hace PERMANENTE. con_nombre() es lo que el recolector mira para no soltar un estrato jamas, asi que los gestos automaticos van SIN nombre y esto es el acto aparte de una persona.",
    },
    Door {
        family: 3,
        name: "volver",
        door: "ES_GESTO_VOLVER",
        value: 8,
        what: "Vuelve a la version arg1 pasos atras. 0 es la de ahora.",
        why: "No copia nada. Los bloques de aquella version siguen todos en el disco --nada se sobreescribio nunca-- asi que volver es publicar UN estrato que apunta a la misma raiz. Volver un volumen de 400 GiB cuesta lo mismo que volver uno vacio.",
    },
    Door {
        family: 3,
        name: "origen",
        door: "ES_GESTO_ORIGEN",
        value: 9,
        what: "DE DONDE SALE EL CONTENIDO: un bloque de KIND_MEMORIA propio.",
        why: "Se pide con RIGHT_READ y no con RIGHT_WRITE: el kernel LEE el bloque, no escribe dentro. Exigir mas autoridad de la que la operacion usa es justo lo que un sistema de capabilities no debe hacer.",
    },
    Door {
        family: 3,
        name: "fichero de",
        door: "ES_GESTO_FICHERO_DE",
        value: 10,
        what: "Crea un fichero con el contenido del bloque anotado en ES_GESTO_ORIGEN. arg1 son los BYTES a tomar.",
        why: "Y quita el rodeo que hoy es obligatorio. Sin esto, la unica forma de meter mas de 96 bytes en ESTRATOS es dejarlos antes en FAT32 y copiarlos con ES_GESTO_COPIA -- o sea que el documento de una aplicacion tiene que pasar por un sistema de ficheros que sobreescribe para llegar al que no sobreescribe. Todo el argumento de ESTRATOS tiene delante un tramo donde no se cumple.",
    },
    Door {
        family: 3,
        name: "guardar",
        door: "ES_GESTO_GUARDAR",
        value: 11,
        what: "GUARDA el contenido del bloque anotado: lo crea, o publica su version nueva. arg1 son los BYTES a tomar, igual que ES_GESTO_FICHERO_DE.",
        why: "Aqui no puede perder nada: el nodo viejo, su contenido y el estrato que lo nombraba siguen enteros y alcanzables. Guardar encima publica una version, no destruye una -- y el historial las muestra las dos.",
    },
    Door {
        family: 4,
        name: "crear",
        door: "ES_RAMA_CREAR",
        value: 12,
        what: "Crea una rama con el nombre que traiga la ruta, en la punta de ahora. No cambia de rama. Devuelve la generacion nueva, o 0.",
        why: "Una rama es un NOMBRE para una punta, guardado FUERA de la historia (la tabla de ramas, D5): ni copia nada ni publica un estrato. Si el volumen no tenia ramas, la de ahora pasa a llamarse principal.",
    },
    Door {
        family: 4,
        name: "cambiar",
        door: "ES_RAMA_CAMBIAR",
        value: 13,
        what: "Cambia a la rama que diga la ruta: el volumen pasa a seguir su punta y la de ahora se queda guardada en la tabla. Devuelve la generacion, o 0.",
        why: "No publica estrato, y por eso nadie se vuelve antepasado de nadie: ir y venir entre ramas no las mezcla. Con volver si pasaba, y era el agujero que la tabla de ramas cerro.",
    },
    Door {
        family: 4,
        name: "contar",
        door: "ES_RAMA_CONTAR",
        value: 14,
        what: "FASE 1 de la mezcla: CUENTA lo que costaria mezclar la rama de la ruta en la de ahora, y apunta sus choques. No escribe nada.",
        why: "DOS FASES porque a mitad de una mezcla el kernel no puede esperar a una persona: tendria una transaccion abierta. Se cuenta, la persona elige con calma, y solo entonces se mezcla.",
    },
    Door {
        family: 4,
        name: "choque",
        door: "ES_RAMA_CHOQUE",
        value: 15,
        what: "Lee un choque de lo contado. arg1 es cual; arg0 >> 8, que trozo.",
        why: "Un choque es un NODO entero con una ruta: lo cambiaron las dos ramas, de formas distintas. Se muestra la ruta y que lado lo tiene; elegir es de la persona (D3).",
    },
    Door {
        family: 4,
        name: "elegir",
        door: "ES_RAMA_ELEGIR",
        value: 16,
        what: "Elige un choque: arg1 es cual, arg0 >> 8 es MEZCLA_A, MEZCLA_B o MEZCLA_QUITAR. Devuelve 1 si se apunto.",
        why: "Se elige un nodo ENTERO, no lineas: un fichero de ESTRATOS no es texto por fuerza, y mezclar bytes de dos versiones a ciegas daria uno que no es ninguno de los dos.",
    },
    Door {
        family: 4,
        name: "mezclar",
        door: "ES_RAMA_MEZCLAR",
        value: 17,
        what: "FASE 2: MEZCLA lo contado con lo elegido. Publica UN estrato de DOS padres: la punta de ahora y la de la otra rama. Devuelve la generacion, o 0.",
        why: "Dice que no sin tocar un sector si hay choques sin elegir, o si el volumen cambio desde que se conto: un plan hecho sobre otro volumen no se aplica. Se vuelve a contar.",
    },
    Door {
        family: 3,
        name: "max",
        door: "ES_GESTO_MAX",
        value: 96,
        what: "Cuanto contenido admite EL RENGLON. Es RESIDENTE_MAX de ESTRATOS: lo que cabe DENTRO del nodo, sin gastar un bloque de datos.",
        why: "ESTO YA NO ES EL TECHO DE UN FICHERO, y llego a serlo por accidente. Dos limites distintos coincidieron en 96 --lo que cabe en el nodo y lo que acumula el renglon-- y el segundo se quedo mandando sobre el primero. ES_GESTO_FICHERO_DE entrega el contenido por un bloque de memoria y no pasa por aqui: este numero solo mide el renglon corto.",
    },
];
