//! GENERADO POR `toolchain/tools/maestros/maestros.py` DESDE EL BANCO DE TITAN++
//! (`toolchain/lang/titan/ejemplos/`) -- NO EDITAR A MANO.
//!
//! Los NODOS MAESTROS de la TAB de F1 (`docs/plan/PLAN_TALLER.md` 8.15): cada
//! programa `BIEN` del banco, que el compilador acepta y los dos bancos corren
//! en cada build. Lo que se edita es el ejemplo; esto lo sigue.

use crate::maestros::Master;
use bmo_titan_contrato::{Permission, Permissions};

/// El nombre de cada familia: el titulo de su nivel en GRAMATICA.md.
pub static FAMILIES: [&str; 14] = [
    "un programa que saluda",
    "calcular",
    "contar",
    "decidir",
    "repetir",
    "funciones con resultado",
    "los tipos",
    "prestar y entregar",
    "casos con datos",
    "varios ficheros",
    "comportamientos",
    "la 3060",
    "lo que viene de fuera",
    "lo que crece",
];

/// Cuantos hay: la TAB mide sus tablas con esto.
pub const COUNT: usize = 37;

/// `static`, no `const`: UNA copia en `.rodata`, que Ring 3 lee por indice
/// sin traerla a una pila de 64 KiB.
pub static MASTERS: [Master; COUNT] = [
    Master {
        name: "dos_saludos",
        level: 0,
        why: "una fn propia, llamada desde main; varios textos en un print; comentarios",
        says: "saluda dos veces",
        words: &["fn"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["hola desde saluda", "hola otra vez"],
        source: "# sale: hola desde saluda\n# sale: hola otra vez\n# una fn propia, llamada desde main; varios textos en un print; comentarios\nmod main \"saluda dos veces\"\n\n# la de verdad\nfn main()\n    saluda()\n    print(\"hola\", \" otra vez\")   # dos textos, uno detras de otro\n\nfn saluda()\n    print(\"hola desde saluda\")\n",
    },
    Master {
        name: "hola",
        level: 0,
        why: "el primer programa: un modulo que dice que hace, y main que saluda",
        says: "saluda",
        words: &["fn"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["hola"],
        source: "# sale: hola\n# el primer programa: un modulo que dice que hace, y main que saluda\nmod main \"saluda\"\n\nfn main()\n    print(\"hola\")\n",
    },
    Master {
        name: "area",
        level: 1,
        why: "el primer calculo: dos valores con nombre y su producto",
        says: "calcula el area de un rectangulo",
        words: &["fn", "let"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["area: 12"],
        source: "# sale: area: 12\n# el primer calculo: dos valores con nombre y su producto\nmod main \"calcula el area de un rectangulo\"\n\nfn main()\n    let ancho = 3\n    let alto = 4\n    let area = ancho * alto\n    print(\"area: \", area)\n",
    },
    Master {
        name: "centauro",
        level: 1,
        why: "textos que se suman, la precedencia de la escuela, el resto, y un negativo",
        says: "el centauro cuenta sus estrellas",
        words: &["fn", "let"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["hola, centauro del espacio", "patas: 4, torso: 1, en total 5", "190 estrellas entre 5 son 38 cada una, y 190 % 7 deja 1", "a 3 de cero: -3"],
        source: "# sale: hola, centauro del espacio\n# sale: patas: 4, torso: 1, en total 5\n# sale: 190 estrellas entre 5 son 38 cada una, y 190 % 7 deja 1\n# sale: a 3 de cero: -3\n# textos que se suman, la precedencia de la escuela, el resto, y un negativo\nmod main \"el centauro cuenta sus estrellas\"\n\nfn main()\n    let saludo = \"hola, \" + \"centauro del espacio\"\n    print(saludo)\n    let patas = 4\n    let torso = 1\n    print(\"patas: \", patas, \", torso: \", torso, \", en total \", patas + torso)\n    let estrellas = 120 + 35 * 2\n    let cada_una = estrellas / 5\n    print(estrellas, \" estrellas entre 5 son \", cada_una, \" cada una, y \", estrellas, \" % 7 deja \", estrellas % 7)\n    print(\"a 3 de cero: \", -(patas - torso))\n",
    },
    Master {
        name: "constelacion",
        level: 2,
        why: "un texto que crece y un numero que acumula, los dos con `mut`",
        says: "dibuja una constelacion",
        words: &["fn", "let", "mut"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["estrellas: * * * *", "brillo total: 26"],
        source: "# sale: estrellas: * * * *\n# sale: brillo total: 26\n# un texto que crece y un numero que acumula, los dos con `mut`\nmod main \"dibuja una constelacion\"\n\nfn main()\n    let mut cielo = \"estrellas:\"\n    let mut brillo = 0\n    cielo = cielo + \" *\"\n    brillo = brillo + 5\n    cielo = cielo + \" *\"\n    brillo = brillo + 7\n    cielo = cielo + \" *\"\n    brillo = brillo + 3\n    cielo = cielo + \" *\"\n    brillo = brillo + 11\n    print(cielo)\n    print(\"brillo total: \", brillo)\n",
    },
    Master {
        name: "contador",
        level: 2,
        why: "contar y acumular: `let mut`, y el mismo nombre a la izquierda y a la derecha",
        says: "el centauro cuenta sus vueltas",
        words: &["fn", "let", "mut"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["el centauro da 3 vueltas al sol", "y junta 60 de energia", "estado: en orbita"],
        source: "# sale: el centauro da 3 vueltas al sol\n# sale: y junta 60 de energia\n# sale: estado: en orbita\n# contar y acumular: `let mut`, y el mismo nombre a la izquierda y a la derecha\nmod main \"el centauro cuenta sus vueltas\"\n\nfn main()\n    let mut vueltas = 0\n    let mut energia = 0\n    vueltas = vueltas + 1\n    energia = energia + vueltas * 10\n    vueltas = vueltas + 1\n    energia = energia + vueltas * 10\n    vueltas = vueltas + 1\n    energia = energia + vueltas * 10\n    print(\"el centauro da \", vueltas, \" vueltas al sol\")\n    print(\"y junta \", energia, \" de energia\")\n    let mut estado = \"en tierra\"\n    estado = \"en orbita\"\n    print(\"estado: \", estado)\n",
    },
    Master {
        name: "calculadora",
        level: 3,
        why: "`if d != 0` guarda la division: el lado que no corre no se calcula",
        says: "una calculadora que no se rompe",
        words: &["fn", "let", "if", "else", "and", "not"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["84 / 0: no se divide entre cero", "84 / 4 = 21", "par y grande: true"],
        source: "# sale: 84 / 0: no se divide entre cero\n# sale: 84 / 4 = 21\n# sale: par y grande: true\n# `if d != 0` guarda la division: el lado que no corre no se calcula\nmod main \"una calculadora que no se rompe\"\n\nfn main()\n    let a = 84\n    let cero = 0\n    if cero != 0\n        print(a, \" / 0 = \", a / cero)\n    else\n        print(a, \" / 0: no se divide entre cero\")\n    let d = 4\n    if d != 0 and a % d == 0\n        print(a, \" / \", d, \" = \", a / d)\n    let par = a % 2 == 0\n    print(\"par y grande: \", par and not (a < 50))\n",
    },
    Master {
        name: "centauro_decide",
        level: 3,
        why: "lo que nace dentro de un bloque vive en su bloque; lo de fuera cambia dentro",
        says: "el centauro decide a donde apunta",
        words: &["fn", "let", "mut", "if", "else", "and"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["el centauro apunta al norte", "flechas: 2"],
        source: "# sale: el centauro apunta al norte\n# sale: flechas: 2\n# lo que nace dentro de un bloque vive en su bloque; lo de fuera cambia dentro\nmod main \"el centauro decide a donde apunta\"\n\nfn main()\n    let mut flechas = 3\n    let noche = true\n    if noche and flechas > 0\n        let rumbo = \"norte\"\n        print(\"el centauro apunta al \", rumbo)\n        flechas = flechas - 1\n    else\n        let rumbo = \"sur\"\n        print(\"el centauro descansa mirando al \", rumbo)\n    print(\"flechas: \", flechas)\n",
    },
    Master {
        name: "semaforo",
        level: 3,
        why: "un `if` con su `else if` y su `else`: un solo camino, decidido al compilar",
        says: "un semaforo que decide",
        words: &["fn", "let", "mut", "if", "else"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["el semaforo esta en ambar", "frena si puedes", "cruzar: false"],
        source: "# sale: el semaforo esta en ambar\n# sale: frena si puedes\n# sale: cruzar: false\n# un `if` con su `else if` y su `else`: un solo camino, decidido al compilar\nmod main \"un semaforo que decide\"\n\nfn main()\n    let segundos = 47\n    let mut color = \"verde\"\n    if segundos > 50\n        color = \"rojo\"\n    else if segundos > 40\n        color = \"ambar\"\n    print(\"el semaforo esta en \", color)\n    if color == \"rojo\"\n        print(\"para\")\n    else if color == \"ambar\"\n        print(\"frena si puedes\")\n    else\n        print(\"pasa\")\n    print(\"cruzar: \", color == \"verde\")\n",
    },
    Master {
        name: "cuenta_atras",
        level: 4,
        why: "`continue` salta a la vuelta siguiente: el 3 no se dice (es de mala suerte)",
        says: "la cuenta atras del centauro",
        words: &["fn", "let", "mut", "if", "while", "continue"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["5", "4", "2", "1", "despegue"],
        source: "# sale: 5\n# sale: 4\n# sale: 2\n# sale: 1\n# sale: despegue\n# `continue` salta a la vuelta siguiente: el 3 no se dice (es de mala suerte)\nmod main \"la cuenta atras del centauro\"\n\nfn main()\n    let mut t = 6\n    while t > 1\n        t = t - 1\n        if t == 3\n            continue\n        print(t)\n    print(\"despegue\")\n",
    },
    Master {
        name: "primos",
        level: 4,
        why: "buscar: un `while` dentro de un `for`, y `break` en cuanto ya se sabe",
        says: "los primos, buscados",
        words: &["fn", "let", "mut", "if", "for", "while", "break"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["primo 2", "primo 3", "primo 5", "primo 7", "primo 11", "primo 13", "primo 17", "primo 19", "8 primos hasta 20"],
        source: "# sale: primo 2\n# sale: primo 3\n# sale: primo 5\n# sale: primo 7\n# sale: primo 11\n# sale: primo 13\n# sale: primo 17\n# sale: primo 19\n# sale: 8 primos hasta 20\n# buscar: un `while` dentro de un `for`, y `break` en cuanto ya se sabe\nmod main \"los primos, buscados\"\n\nfn main()\n    let mut cuantos = 0\n    for n in range(2, 21)\n        let mut d = 2\n        let mut primo = true\n        while d * d <= n\n            if n % d == 0\n                primo = false\n                break\n            d = d + 1\n        if primo\n            print(\"primo \", n)\n            cuantos = cuantos + 1\n    print(cuantos, \" primos hasta 20\")\n",
    },
    Master {
        name: "salta_y_sigue",
        level: 4,
        why: "`continue` y `break` dentro de un `if`, y el nombre de la vuelta leido despues: el camino que sigue lo tiene vivo (08-10: antes paraba el compilador)",
        says: "los impares, saltando los pares",
        words: &["fn", "let", "mut", "if", "for", "break", "continue"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["1", "3", "5", "suma de los impares hasta 6: 9"],
        source: "# sale: 1\n# sale: 3\n# sale: 5\n# sale: suma de los impares hasta 6: 9\n# `continue` y `break` dentro de un `if`, y el nombre de la vuelta leido despues: el camino que sigue lo tiene vivo (08-10: antes paraba el compilador)\nmod main \"los impares, saltando los pares\"\n\nfn main()\n    let mut suma = 0\n    for i in range(1, 100)\n        if i % 2 == 0\n            continue\n        if i > 6\n            break\n        print(i)\n        suma = suma + i\n    print(\"suma de los impares hasta 6: \", suma)\n",
    },
    Master {
        name: "tabla_del_siete",
        level: 4,
        why: "un `for` cuenta solo: `i` es nuevo en cada vuelta y nadie mas lo cambia",
        says: "la tabla del siete",
        words: &["fn", "let", "mut", "for"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["7 x 1 = 7", "7 x 2 = 14", "7 x 3 = 21", "7 x 4 = 28", "7 x 5 = 35", "la tabla suma 105"],
        source: "# sale: 7 x 1 = 7\n# sale: 7 x 2 = 14\n# sale: 7 x 3 = 21\n# sale: 7 x 4 = 28\n# sale: 7 x 5 = 35\n# sale: la tabla suma 105\n# un `for` cuenta solo: `i` es nuevo en cada vuelta y nadie mas lo cambia\nmod main \"la tabla del siete\"\n\nfn main()\n    let mut suma = 0\n    for i in range(1, 6)\n        print(\"7 x \", i, \" = \", 7 * i)\n        suma = suma + 7 * i\n    print(\"la tabla suma \", suma)\n",
    },
    Master {
        name: "euclides",
        level: 5,
        why: "el maximo comun divisor de Euclides (300 a. C.) y una funcion que responde si o no",
        says: "Euclides y los primos",
        words: &["fn", "let", "mut", "if", "while", "return"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["mcd(48, 18) = 6", "mcd(1071, 462) = 21", "17 es primo: true", "21 es primo: false"],
        source: "# sale: mcd(48, 18) = 6\n# sale: mcd(1071, 462) = 21\n# sale: 17 es primo: true\n# sale: 21 es primo: false\n# el maximo comun divisor de Euclides (300 a. C.) y una funcion que responde si o no\nmod main \"Euclides y los primos\"\n\nfn mcd(a: int, b: int) -> int\n    if b == 0\n        return a\n    return mcd(b, a % b)\n\nfn es_primo(n: int) -> bool\n    if n < 2\n        return false\n    let mut d = 2\n    while d * d <= n\n        if n % d == 0\n            return false\n        d = d + 1\n    return true\n\nfn main()\n    print(\"mcd(48, 18) = \", mcd(48, 18))\n    print(\"mcd(1071, 462) = \", mcd(1071, 462))\n    print(\"17 es primo: \", es_primo(17))\n    print(\"21 es primo: \", es_primo(21))\n",
    },
    Master {
        name: "factorial",
        level: 5,
        why: "una funcion que se llama a si misma, con su caso de parada: la recursion",
        says: "el factorial, recursivo",
        words: &["fn", "if", "for", "return"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["1! = 1", "2! = 2", "3! = 6", "4! = 24", "5! = 120", "6! = 720"],
        source: "# sale: 1! = 1\n# sale: 2! = 2\n# sale: 3! = 6\n# sale: 4! = 24\n# sale: 5! = 120\n# sale: 6! = 720\n# una funcion que se llama a si misma, con su caso de parada: la recursion\nmod main \"el factorial, recursivo\"\n\nfn factorial(n: int) -> int\n    if n <= 1\n        return 1\n    return n * factorial(n - 1)\n\nfn main()\n    for i in range(1, 7)\n        print(i, \"! = \", factorial(i))\n",
    },
    Master {
        name: "fibonacci",
        level: 5,
        why: "texto que crece con un `mut`, y una funcion con dos parametros",
        says: "la espiral del centauro",
        words: &["fn", "let", "mut", "if", "for", "return"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["0 1 1 2 3 5 8 13 21 34", "el centauro cuenta 55 estrellas"],
        source: "# sale: 0 1 1 2 3 5 8 13 21 34\n# sale: el centauro cuenta 55 estrellas\n# texto que crece con un `mut`, y una funcion con dos parametros\nmod main \"la espiral del centauro\"\n\nfn fib(n: int) -> int\n    if n < 2\n        return n\n    return fib(n - 1) + fib(n - 2)\n\nfn con_espacio(a: text, b: text) -> text\n    if a == \"\"\n        return b\n    return a + \" \" + b\n\nfn main()\n    let mut linea = \"\"\n    for i in range(10)\n        linea = con_espacio(linea, digitos(fib(i)))\n    print(linea)\n    print(\"el centauro cuenta \", fib(10), \" estrellas\")\n\nfn digitos(n: int) -> text\n    if n < 10\n        return cifra(n)\n    # (n - n % 10) / 10 siempre es exacto: TITAN++ no redondea a escondidas\n    return digitos((n - n % 10) / 10) + cifra(n % 10)\n\nfn cifra(n: int) -> text\n    if n == 0\n        return \"0\"\n    if n == 1\n        return \"1\"\n    if n == 2\n        return \"2\"\n    if n == 3\n        return \"3\"\n    if n == 4\n        return \"4\"\n    if n == 5\n        return \"5\"\n    if n == 6\n        return \"6\"\n    if n == 7\n        return \"7\"\n    if n == 8\n        return \"8\"\n    return \"9\"\n",
    },
    Master {
        name: "factura",
        level: 6,
        why: "el dinero en `dec`: exacto, sin float, y nada se redondea solo",
        says: "una factura que no pierde centimos",
        words: &["fn", "let", "mut", "for", "return", "type", "dec"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["cafe x 2 = 3.50", "pan x 3 = 2.70", "queso x 1 = 4.25", "total: 10.45", "con 21% de IVA: 12.6445", "entre 4 amigos: 3.161125"],
        source: "# sale: cafe x 2 = 3.50\n# sale: pan x 3 = 2.70\n# sale: queso x 1 = 4.25\n# sale: total: 10.45\n# sale: con 21% de IVA: 12.6445\n# sale: entre 4 amigos: 3.161125\n# el dinero en `dec`: exacto, sin float, y nada se redondea solo\nmod main \"una factura que no pierde centimos\"\n\ntype Linea\n    cosa: text\n    precio: dec\n    cantidad: int\n\nfn importe(l: Linea) -> dec\n    return l.precio * l.cantidad\n\nfn main()\n    let compra = [Linea { cosa: \"cafe\", precio: 1.75, cantidad: 2 }, Linea { cosa: \"pan\", precio: 0.90, cantidad: 3 }, Linea { cosa: \"queso\", precio: 4.25, cantidad: 1 }]\n    let mut total = 0.00\n    for l in compra\n        print(l.cosa, \" x \", l.cantidad, \" = \", importe(l))\n        total = total + importe(l)\n    print(\"total: \", total)\n    let con_iva = total * 1.21\n    print(\"con 21% de IVA: \", con_iva)\n    print(\"entre 4 amigos: \", con_iva / 4)\n",
    },
    Master {
        name: "flota",
        level: 6,
        why: "un `type` con campos, una tabla de ellos, y cambiar un campo con `mut`",
        says: "la flota del centauro",
        words: &["fn", "let", "mut", "for", "return", "type", "dec"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["Nave { nombre: \"centauro\", x: 0.0, combustible: 50.00 }", "centauro avanza a 7.5 con 47.00", "flota: 3 naves, 141.00 de combustible"],
        source: "# sale: Nave { nombre: \"centauro\", x: 0.0, combustible: 50.00 }\n# sale: centauro avanza a 7.5 con 47.00\n# sale: flota: 3 naves, 141.00 de combustible\n# un `type` con campos, una tabla de ellos, y cambiar un campo con `mut`\nmod main \"la flota del centauro\"\n\ntype Nave\n    nombre: text\n    x: dec\n    combustible: dec\n\nfn total(f: [Nave; 3]) -> dec\n    let mut suma = 0.00\n    for n in f\n        suma = suma + n.combustible\n    return suma\n\nfn main()\n    let mut lider = Nave { nombre: \"centauro\", x: 0.0, combustible: 50.00 }\n    print(lider)\n    lider.x = lider.x + 7.5\n    lider.combustible = lider.combustible - 3\n    print(lider.nombre, \" avanza a \", lider.x, \" con \", lider.combustible)\n    let flota = [lider, Nave { nombre: \"orion\", x: 2.0, combustible: 44.00 }, Nave { nombre: \"lyra\", x: 4.0, combustible: 50.00 }]\n    print(\"flota: \", len(flota), \" naves, \", total(flota), \" de combustible\")\n",
    },
    Master {
        name: "ordenar",
        level: 6,
        why: "ordenar una tabla: la burbuja, celda a celda, con `mut`",
        says: "la burbuja del centauro",
        words: &["fn", "let", "mut", "if", "for"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["antes: [5, 2, 9, 1, 7]", "despues: [1, 2, 5, 7, 9]", "el mayor es 9, en la celda 4"],
        source: "# sale: antes: [5, 2, 9, 1, 7]\n# sale: despues: [1, 2, 5, 7, 9]\n# sale: el mayor es 9, en la celda 4\n# ordenar una tabla: la burbuja, celda a celda, con `mut`\nmod main \"la burbuja del centauro\"\n\nfn main()\n    let mut t = [5, 2, 9, 1, 7]\n    print(\"antes: \", t)\n    let n = len(t)\n    for i in range(n)\n        for j in range(n - 1 - i)\n            if t[j] > t[j + 1]\n                let menor = t[j + 1]\n                t[j + 1] = t[j]\n                t[j] = menor\n    print(\"despues: \", t)\n    print(\"el mayor es \", t[n - 1], \", en la celda \", n - 1)\n",
    },
    Master {
        name: "banco",
        level: 7,
        why: "precision de COBOL: cada saldo declara sus cifras (dec(9, 2)) y el redondeo se ESCRIBE",
        says: "un banco que no pierde un centimo",
        words: &["fn", "let", "mut", "return", "type", "dec", "round"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["ana tiene 1250.00", "tras el interes: 1278.13", "tras pagar 99.99: 1178.14", "el interes redondeado a la vista: 28.1250 -> 28.13"],
        source: "# sale: ana tiene 1250.00\n# sale: tras el interes: 1278.13\n# sale: tras pagar 99.99: 1178.14\n# sale: el interes redondeado a la vista: 28.1250 -> 28.13\n# precision de COBOL: cada saldo declara sus cifras (dec(9, 2)) y el redondeo se ESCRIBE\nmod main \"un banco que no pierde un centimo\"\n\ntype Cuenta\n    titular: text\n    saldo: dec(9, 2)\n\nfn interes(saldo: dec(9, 2), tasa: dec(5, 4)) -> dec(9, 2)\n    # 1250.00 * 0.0225 = 28.125: tres decimales, y el saldo guarda dos\n    return round(saldo * tasa, 2)\n\nfn abona(mut c: Cuenta, tasa: dec(5, 4))\n    c.saldo = c.saldo + interes(c.saldo, tasa)\n\nfn paga(mut c: Cuenta, importe: dec(9, 2))\n    c.saldo = c.saldo - importe\n\nfn main()\n    let mut ana = Cuenta { titular: \"ana\", saldo: 1250 }\n    print(ana.titular, \" tiene \", ana.saldo)\n    abona(mut ana, 0.0225)\n    print(\"tras el interes: \", ana.saldo)\n    paga(mut ana, 99.99)\n    print(\"tras pagar 99.99: \", ana.saldo)\n    print(\"el interes redondeado a la vista: \", 1250.00 * 0.0225, \" -> \", interes(1250.00, 0.0225))\n",
    },
    Master {
        name: "hundir",
        level: 7,
        why: "`take` entrega la nave: quien la recibe se la queda, y el que llama ya no la tiene",
        says: "una nave que se entrega",
        words: &["fn", "let", "return", "type", "dec", "take"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["orion se hunde con 44.00 de combustible", "la flota sigue con centauro"],
        source: "# sale: orion se hunde con 44.00 de combustible\n# sale: la flota sigue con centauro\n# `take` entrega la nave: quien la recibe se la queda, y el que llama ya no la tiene\nmod main \"una nave que se entrega\"\n\ntype Nave\n    nombre: text\n    combustible: dec(5, 2)\n\nfn hunde(take n: Nave) -> text\n    return n.nombre\n\nfn combustible(n: Nave) -> dec(5, 2)\n    return n.combustible\n\nfn main()\n    let lider = Nave { nombre: \"centauro\", combustible: 50 }\n    let vieja = Nave { nombre: \"orion\", combustible: 44 }\n    let queda = combustible(vieja)\n    let quien = hunde(take vieja)\n    print(quien, \" se hunde con \", queda, \" de combustible\")\n    print(\"la flota sigue con \", lider.nombre)\n",
    },
    Master {
        name: "ordena_prestada",
        level: 7,
        why: "`mut` presta la tabla: la funcion la ordena EN SU SITIO, sin copiarla, y se ve al volver",
        says: "ordenar sin copiar",
        words: &["fn", "let", "mut", "if", "for"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["[1, 2, 4, 7, 9]", "[9, 7, 4, 2, 1]"],
        source: "# sale: [1, 2, 4, 7, 9]\n# sale: [9, 7, 4, 2, 1]\n# `mut` presta la tabla: la funcion la ordena EN SU SITIO, sin copiarla, y se ve al volver\nmod main \"ordenar sin copiar\"\n\nfn ordena(mut t: [int; 5])\n    for i in range(5)\n        for j in range(4 - i)\n            if t[j] > t[j + 1]\n                let m = t[j + 1]\n                t[j + 1] = t[j]\n                t[j] = m\n\nfn da_la_vuelta(mut t: [int; 5])\n    for i in range(2)\n        let m = t[i]\n        t[i] = t[4 - i]\n        t[4 - i] = m\n\nfn main()\n    let mut t = [7, 2, 9, 1, 4]\n    ordena(mut t)\n    print(t)\n    da_la_vuelta(mut t)\n    print(t)\n",
    },
    Master {
        name: "formas",
        level: 8,
        why: "un `enum` dice que FORMAS puede tener un valor, y cada una lleva sus datos",
        says: "areas sin preguntar dos veces",
        words: &["fn", "let", "mut", "for", "return", "dec", "enum", "match"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["Circulo(2.0) mide 12.56", "Rect(3.5, 2) mide 7.0", "Nada mide 0", "total: 19.56"],
        source: "# sale: Circulo(2.0) mide 12.56\n# sale: Rect(3.5, 2) mide 7.0\n# sale: Nada mide 0\n# sale: total: 19.56\n# un `enum` dice que FORMAS puede tener un valor, y cada una lleva sus datos\nmod main \"areas sin preguntar dos veces\"\n\nenum Forma\n    Circulo(dec)\n    Rect(dec, dec)\n    Nada\n\nfn area(f: Forma) -> dec\n    match f\n        Circulo(r)\n            return 3.14 * r * r\n        Rect(ancho, alto)\n            return ancho * alto\n        Nada\n            return 0\n\nfn main()\n    let formas = [Circulo(2.0), Rect(3.5, 2), Nada]\n    let mut total = 0.00\n    for f in formas\n        print(f, \" mide \", area(f))\n        total = total + area(f)\n    print(\"total: \", total)\n",
    },
    Master {
        name: "pago",
        level: 8,
        why: "sin null y sin excepciones: lo que puede salir mal es un CASO, y el `match` obliga a mirarlo",
        says: "un cobro que dice por que no",
        words: &["fn", "let", "if", "return", "dec", "enum", "match"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["cobrado 120.50, queda 379.50", "rechazado: faltan 20.50", "el resultado guarda su caso: true"],
        source: "# sale: cobrado 120.50, queda 379.50\n# sale: rechazado: faltan 20.50\n# sale: el resultado guarda su caso: true\n# sin null y sin excepciones: lo que puede salir mal es un CASO, y el `match` obliga a mirarlo\nmod main \"un cobro que dice por que no\"\n\nenum Cobro\n    Hecho(dec(9, 2))\n    Falta(dec(9, 2))\n\nfn cobra(saldo: dec(9, 2), importe: dec(9, 2)) -> Cobro\n    if importe > saldo\n        return Falta(importe - saldo)\n    return Hecho(saldo - importe)\n\nfn cuenta(c: Cobro, importe: dec(9, 2))\n    match c\n        Hecho(queda)\n            print(\"cobrado \", importe, \", queda \", queda)\n        Falta(cuanto)\n            print(\"rechazado: faltan \", cuanto)\n\nfn main()\n    let saldo: dec(9, 2) = 500.00\n    cuenta(cobra(saldo, 120.50), 120.50)\n    let mal = cobra(100.00, 120.50)\n    cuenta(mal, 120.50)\n    print(\"el resultado guarda su caso: \", mal == Falta(20.5))\n",
    },
    Master {
        name: "semaforo",
        level: 8,
        why: "casos sin datos: un semaforo que no puede estar en un color que no existe",
        says: "un semaforo de tres colores",
        words: &["fn", "let", "mut", "for", "return", "enum", "match"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["Verde: pasa", "Ambar: frena", "Rojo: espera", "Verde: pasa"],
        source: "# sale: Verde: pasa\n# sale: Ambar: frena\n# sale: Rojo: espera\n# sale: Verde: pasa\n# casos sin datos: un semaforo que no puede estar en un color que no existe\nmod main \"un semaforo de tres colores\"\n\nenum Luz\n    Verde\n    Ambar\n    Rojo\n\nfn siguiente(l: Luz) -> Luz\n    match l\n        Verde\n            return Ambar\n        Ambar\n            return Rojo\n        Rojo\n            return Verde\n\nfn main()\n    let mut luz = Verde\n    for i in range(4)\n        match luz\n            Verde\n                print(luz, \": pasa\")\n            Ambar\n                print(luz, \": frena\")\n            Rojo\n                print(luz, \": espera\")\n        luz = siguiente(luz)\n",
    },
    Master {
        name: "con_permiso",
        level: 9,
        why: "el Titan.toml PIDE, y la cabecera usa lo pedido: el .bex lleva esos permisos a su manifiesto",
        says: "un paquete que pide lo que usa",
        words: &["fn", "use", "gpu"],
        asks: Permissions::NONE.with(Permission::Screen).with(Permission::Gpu),
        typed: &[],
        out: &["pide la 3060 y la pantalla, y su .bex lo dice"],
        source: "# sale: pide la 3060 y la pantalla, y su .bex lo dice\n# el Titan.toml PIDE, y la cabecera usa lo pedido: el .bex lleva esos permisos a su manifiesto\nmod main \"un paquete que pide lo que usa\"\nuse gpu, director\n\nfn main()\n    print(\"pide la 3060 y la pantalla, y su .bex lo dice\")\n",
    },
    Master {
        name: "formas",
        level: 10,
        why: "`trait` dice lo que una forma SABE hacer; cada tipo dice COMO, y `mide` vale para todas",
        says: "formas que se saben medir",
        words: &["fn", "let", "mut", "if", "else", "for", "return", "type", "dec", "trait"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["un Circulo: 12.56", "un Cuadrado: 9.00", "el mas grande mide 12.56", "centauro crece hasta 2"],
        source: "# sale: un Circulo: 12.56\n# sale: un Cuadrado: 9.00\n# sale: el mas grande mide 12.56\n# sale: centauro crece hasta 2\n# `trait` dice lo que una forma SABE hacer; cada tipo dice COMO, y `mide` vale para todas\nmod main \"formas que se saben medir\"\n\ntrait Forma\n    fn area(f: Forma) -> dec\n    fn nombre(f: Forma) -> text\n\ntype Circulo\n    r: dec\n\ntype Cuadrado\n    lado: dec\n\ntrait Forma for Circulo\n    fn area(c: Circulo) -> dec\n        return 3.14 * c.r * c.r\n    fn nombre(c: Circulo) -> text\n        return \"Circulo\"\n\ntrait Forma for Cuadrado\n    fn area(q: Cuadrado) -> dec\n        return q.lado * q.lado\n    fn nombre(q: Cuadrado) -> text\n        return \"Cuadrado\"\n\nfn describe(f: Forma) -> dec\n    print(\"un \", nombre(f), \": \", area(f))\n    return area(f)\n\ntrait Crece\n    fn crece(mut x: Crece)\n\ntype Nave\n    nombre: text\n    nivel: int\n\ntrait Crece for Nave\n    fn crece(mut n: Nave)\n        n.nivel = n.nivel + 1\n\nfn sube(mut x: Crece)\n    crece(mut x)\n\nfn main()\n    let a = describe(Circulo { r: 2.0 })\n    let b = describe(Cuadrado { lado: 3.00 })\n    if a > b\n        print(\"el mas grande mide \", a)\n    else\n        print(\"el mas grande mide \", b)\n    let mut n = Nave { nombre: \"centauro\", nivel: 0 }\n    sube(mut n)\n    sube(mut n)\n    print(n.nombre, \" crece hasta \", n.nivel)\n",
    },
    Master {
        name: "activa",
        level: 11,
        why: "el f32 cuenta en la 3060, con sus redondeos de base 2; vuelve a la CPU con round, a la vista",
        says: "lo que la 3060 redondea, dicho en voz alta",
        words: &["fn", "let", "if", "return", "round", "gpu", "f32"],
        asks: Permissions::NONE.with(Permission::Gpu),
        typed: &[],
        out: &["0.1 + 0.2 en la 3060, a 9 decimales: 0.300000012", "el mismo, redondeado a 2: 0.30", "en la CPU, con dec: 0.3", "activa: 0.000 1.500 0.000"],
        source: "# sale: 0.1 + 0.2 en la 3060, a 9 decimales: 0.300000012\n# sale: el mismo, redondeado a 2: 0.30\n# sale: en la CPU, con dec: 0.3\n# sale: activa: 0.000 1.500 0.000\n# el f32 cuenta en la 3060, con sus redondeos de base 2; vuelve a la CPU con round, a la vista\nmod main \"lo que la 3060 redondea, dicho en voz alta\"\n\ngpu fn suma(a: f32, b: f32) -> f32\n    return a + b\n\ngpu fn activa(x: f32) -> f32\n    if x > 0.0\n        return x\n    return 0.0\n\nfn main()\n    let a: [f32; 1] = [0.1]\n    let b: [f32; 1] = [0.2]\n    let s = suma(a, b)\n    print(\"0.1 + 0.2 en la 3060, a 9 decimales: \", round(s[0], 9))\n    print(\"el mismo, redondeado a 2: \", round(s[0], 2))\n    print(\"en la CPU, con dec: \", 0.1 + 0.2)\n    let xs: [f32; 3] = [-2.0, 1.5, 0.0]\n    let r = activa(xs)\n    print(\"activa: \", round(r[0], 3), \" \", round(r[1], 3), \" \", round(r[2], 3))\n",
    },
    Master {
        name: "bucles",
        level: 11,
        why: "un `for` dentro de una gpu fn (LB5): sus vueltas ESCRITAS, asi que el hilo acaba por construccion; `break` y `continue` tambien",
        says: "los bucles de un hilo",
        words: &["fn", "let", "mut", "if", "for", "break", "continue", "return", "round", "gpu", "f32"],
        asks: Permissions::NONE.with(Permission::Gpu),
        typed: &[],
        out: &["2 a la 10: 1024", "1 + x + ... + x^7, con x = 0.5: 1.9921875", "e, por diez cuadrados en f32: 2.71694", "sumando 0, 1, 2, 4... hasta pasar de 20 y de 4: 25 7"],
        source: "# sale: 2 a la 10: 1024\n# sale: 1 + x + ... + x^7, con x = 0.5: 1.9921875\n# sale: e, por diez cuadrados en f32: 2.71694\n# sale: sumando 0, 1, 2, 4... hasta pasar de 20 y de 4: 25 7\n# un `for` dentro de una gpu fn (LB5): sus vueltas ESCRITAS, asi que el hilo acaba por construccion; `break` y `continue` tambien\nmod main \"los bucles de un hilo\"\n\ngpu fn potencia(x: f32) -> f32\n    let mut r = 1.0\n    for i in range(10)\n        r = r * x\n    return r\n\ngpu fn serie(x: f32) -> f32\n    let mut s = 0.0\n    let mut t = 1.0\n    for k in range(8)\n        s = s + t\n        t = t * x\n    return s\n\ngpu fn e(x: f32) -> f32\n    let mut y = 1.0 + x / 1024.0\n    for i in range(10)\n        y = y * y\n    return y\n\ngpu fn hasta(tope: f32) -> f32\n    let mut s = 0.0\n    for i in range(100)\n        if i == 3.0\n            continue\n        s = s + i\n        if s > tope\n            break\n    return s\n\nfn main()\n    let dos: [f32; 1] = [2.0]\n    let medio: [f32; 1] = [0.5]\n    let uno: [f32; 1] = [1.0]\n    let topes: [f32; 2] = [20.0, 4.0]\n    let p = potencia(dos)\n    let s = serie(medio)\n    let y = e(uno)\n    let h = hasta(topes)\n    print(\"2 a la 10: \", round(p[0], 0))\n    print(\"1 + x + ... + x^7, con x = 0.5: \", round(s[0], 7))\n    print(\"e, por diez cuadrados en f32: \", round(y[0], 5))\n    print(\"sumando 0, 1, 2, 4... hasta pasar de 20 y de 4: \", round(h[0], 0), \" \", round(h[1], 0))\n",
    },
    Master {
        name: "mezcla",
        level: 11,
        why: "una gpu fn se escribe para UNA celda; con tablas de 4, son 4 hilos de la 3060",
        says: "la 3060 mezcla dos tablas",
        words: &["fn", "let", "for", "return", "round", "gpu", "f32"],
        asks: Permissions::NONE.with(Permission::Gpu),
        typed: &[],
        out: &["2.00", "2.00", "2.00", "2.25"],
        source: "# sale: 2.00\n# sale: 2.00\n# sale: 2.00\n# sale: 2.25\n# una gpu fn se escribe para UNA celda; con tablas de 4, son 4 hilos de la 3060\nmod main \"la 3060 mezcla dos tablas\"\n\ngpu fn mezcla(a: f32, b: f32) -> f32\n    return (a + b) / 2.0\n\nfn main()\n    let xs: [f32; 4] = [1.0, 2.0, 3.0, 4.0]\n    let ys: [f32; 4] = [3.0, 2.0, 1.0, 0.5]\n    let c = mezcla(xs, ys)\n    for x in c\n        print(round(x, 2))\n",
    },
    Master {
        name: "adivina",
        level: 12,
        why: "`numero(t)` da un CASO: Es(n) si lo tecleado es un numero, NoEs si no -- y el `match` obliga a mirar los dos",
        says: "adivina el numero",
        words: &["fn", "let", "mut", "if", "else", "not", "while", "match"],
        asks: Permissions::NONE,
        typed: &["50", "setenta", "80", "  73"],
        out: &["adivina el numero (de 1 a 100)", "mas alto", "eso no es un numero: setenta", "mas bajo", "si! era 73, y lo sacaste en 3 intentos"],
        source: "# entra: 50\n# entra: setenta\n# entra: 80\n# entra:   73\n# sale: adivina el numero (de 1 a 100)\n# sale: mas alto\n# sale: eso no es un numero: setenta\n# sale: mas bajo\n# sale: si! era 73, y lo sacaste en 3 intentos\n# `numero(t)` da un CASO: Es(n) si lo tecleado es un numero, NoEs si no -- y el `match` obliga a mirar los dos\nmod main \"adivina el numero\"\n\nfn main()\n    let secreto = 73\n    print(\"adivina el numero (de 1 a 100)\")\n    let mut intentos = 0\n    let mut acertado = false\n    while not acertado\n        let t = lee()\n        match numero(t)\n            Es(n)\n                intentos = intentos + 1\n                if n < secreto\n                    print(\"mas alto\")\n                else if n > secreto\n                    print(\"mas bajo\")\n                else\n                    acertado = true\n            NoEs\n                print(\"eso no es un numero: \", t)\n    print(\"si! era \", secreto, \", y lo sacaste en \", intentos, \" intentos\")\n",
    },
    Master {
        name: "hasta_fin",
        level: 12,
        why: "un `while` que para cuando LO TECLEADO lo dice: nadie sabia al compilar cuantas vueltas daria",
        says: "la lista de la compra",
        words: &["fn", "let", "mut", "while"],
        asks: Permissions::NONE,
        typed: &["pan", "leche", "huevos", "fin"],
        out: &["apunta lo que falta; fin para terminar", "1: pan", "2: leche", "3: huevos", "son 3 cosas"],
        source: "# entra: pan\n# entra: leche\n# entra: huevos\n# entra: fin\n# sale: apunta lo que falta; fin para terminar\n# sale: 1: pan\n# sale: 2: leche\n# sale: 3: huevos\n# sale: son 3 cosas\n# un `while` que para cuando LO TECLEADO lo dice: nadie sabia al compilar cuantas vueltas daria\nmod main \"la lista de la compra\"\n\nfn main()\n    print(\"apunta lo que falta; fin para terminar\")\n    let mut n = 0\n    let mut cosa = lee()\n    while cosa != \"fin\"\n        n = n + 1\n        print(n, \": \", cosa)\n        cosa = lee()\n    print(\"son \", n, \" cosas\")\n",
    },
    Master {
        name: "la_cuenta",
        level: 12,
        why: "lo tecleado entra al dinero exacto: 3 cafes de 1.80 son 5.40, y el reparto se redondea A LA VISTA, nunca a escondidas",
        says: "la cuenta del bar",
        words: &["fn", "let", "if", "else", "return", "round", "match"],
        asks: Permissions::NONE,
        typed: &["3", "2", "4"],
        out: &["cafes?", "tostadas?", "entre cuantos?", "cafes 5.40, tostadas 4.70", "total 10.10, con IVA 11.11", "toca a 2.78 cada uno (redondeado: lo dice el round)"],
        source: "# entra: 3\n# entra: 2\n# entra: 4\n# sale: cafes?\n# sale: tostadas?\n# sale: entre cuantos?\n# sale: cafes 5.40, tostadas 4.70\n# sale: total 10.10, con IVA 11.11\n# sale: toca a 2.78 cada uno (redondeado: lo dice el round)\n# lo tecleado entra al dinero exacto: 3 cafes de 1.80 son 5.40, y el reparto se redondea A LA VISTA, nunca a escondidas\nmod main \"la cuenta del bar\"\n\nfn pide(que: text) -> int\n    print(que, \"?\")\n    match numero(lee())\n        Es(n)\n            return n\n        NoEs\n            return 0\n\nfn main()\n    let cafes = pide(\"cafes\")\n    let tostadas = pide(\"tostadas\")\n    let gente = pide(\"entre cuantos\")\n    let c = cafes * 1.80\n    let t = tostadas * 2.35\n    print(\"cafes \", c, \", tostadas \", t)\n    let total = c + t\n    let con_iva = round(total * 1.10, 2)\n    print(\"total \", total, \", con IVA \", con_iva)\n    if gente > 0\n        print(\"toca a \", round(con_iva / gente, 2), \" cada uno (redondeado: lo dice el round)\")\n    else\n        print(\"nadie paga?\")\n",
    },
    Master {
        name: "pregunta",
        level: 12,
        why: "el primer programa que PREGUNTA: lo que escribe depende de lo que se teclea, y por eso corre de verdad en la maquina",
        says: "saluda a quien teclee su nombre",
        words: &["fn", "let"],
        asks: Permissions::NONE,
        typed: &["Ada"],
        out: &["como te llamas?", "hola Ada!"],
        source: "# entra: Ada\n# sale: como te llamas?\n# sale: hola Ada!\n# el primer programa que PREGUNTA: lo que escribe depende de lo que se teclea, y por eso corre de verdad en la maquina\nmod main \"saluda a quien teclee su nombre\"\n\nfn main()\n    print(\"como te llamas?\")\n    let nombre = lee()\n    print(\"hola \", nombre, \"!\")\n",
    },
    Master {
        name: "reserva",
        level: 12,
        why: "lo tecleado entra a f32 por su tipo declarado, y la gpu fn corre AL CORRER: en la CPU, su reserva (LB4)",
        says: "una gpu fn con lo que se teclea",
        words: &["fn", "let", "if", "return", "round", "match", "gpu", "f32"],
        asks: Permissions::NONE.with(Permission::Gpu),
        typed: &["3", "5"],
        out: &["la media de 3 y 5, por la gpu fn: 4.00", "activa con -3, 0 y 5: 0.0 0.0 5.0", "un dec tecleado, a f32 y de vuelta: 0.125"],
        source: "# entra: 3\n# entra: 5\n# sale: la media de 3 y 5, por la gpu fn: 4.00\n# sale: activa con -3, 0 y 5: 0.0 0.0 5.0\n# sale: un dec tecleado, a f32 y de vuelta: 0.125\n# lo tecleado entra a f32 por su tipo declarado, y la gpu fn corre AL CORRER: en la CPU, su reserva (LB4)\nmod main \"una gpu fn con lo que se teclea\"\n\ngpu fn media(a: f32, b: f32) -> f32\n    return (a + b) / 2.0\n\ngpu fn activa(x: f32) -> f32\n    if x > 0.0\n        return x\n    return 0.0\n\nfn entero(t: text) -> int\n    match numero(t)\n        Es(n)\n            return n\n        NoEs\n            return 0\n\nfn main()\n    let x = entero(lee())\n    let y = entero(lee())\n    let a: f32 = x\n    let b: f32 = y\n    let m = media(a, b)\n    print(\"la media de \", x, \" y \", y, \", por la gpu fn: \", round(m, 2))\n    let menos: f32 = 0 - x\n    let cero: f32 = 0\n    let xs: [f32; 3] = [menos, cero, b]\n    let r = activa(xs)\n    print(\"activa con \", 0 - x, \", 0 y \", y, \": \", round(r[0], 1), \" \", round(r[1], 1), \" \", round(r[2], 1))\n    let d: f32 = y * 0.025\n    print(\"un dec tecleado, a f32 y de vuelta: \", round(d, 3))\n",
    },
    Master {
        name: "agenda",
        level: 13,
        why: "una lista que CRECE con lo tecleado y un mapa que cuenta: nadie sabia al compilar cuantos serian",
        says: "la agenda que cuenta",
        words: &["fn", "let", "mut", "for", "while", "match"],
        asks: Permissions::NONE,
        typed: &["Ada", "Grace", "Ada", "Linus", "fin"],
        out: &["nombres, uno por linea; fin para terminar", "4 apuntados, 3 distintos", "Ada: 2", "Grace: 1", "Linus: 1", "el ultimo fue Linus"],
        source: "# entra: Ada\n# entra: Grace\n# entra: Ada\n# entra: Linus\n# entra: fin\n# sale: nombres, uno por linea; fin para terminar\n# sale: 4 apuntados, 3 distintos\n# sale: Ada: 2\n# sale: Grace: 1\n# sale: Linus: 1\n# sale: el ultimo fue Linus\n# una lista que CRECE con lo tecleado y un mapa que cuenta: nadie sabia al compilar cuantos serian\nmod main \"la agenda que cuenta\"\n\nfn main()\n    print(\"nombres, uno por linea; fin para terminar\")\n    let mut todos: [text] = []\n    let mut veces: {text: int} = {}\n    let mut nombre = lee()\n    while nombre != \"fin\"\n        push(mut todos, nombre)\n        match get(veces, nombre)\n            Hay(n)\n                put(mut veces, nombre, n + 1)\n            NoHay\n                put(mut veces, nombre, 1)\n        nombre = lee()\n    print(len(todos), \" apuntados, \", len(veces), \" distintos\")\n    for k in veces\n        match get(veces, k)\n            Hay(n)\n                print(k, \": \", n)\n            NoHay\n                print(k, \": ?\")\n    match pop(mut todos)\n        Hay(u)\n            print(\"el ultimo fue \", u)\n        NoHay\n            print(\"no se apunto nadie\")\n",
    },
    Master {
        name: "mundo",
        level: 13,
        why: "un mundo de cubos en chico: cada bloque, por su SITIO -- un mapa cuya clave es un registro",
        says: "un mundo de bloques",
        words: &["fn", "let", "mut", "if", "for", "type", "match"],
        asks: Permissions::NONE,
        typed: &[],
        out: &["..~~.", ".#~~.", "##...", "el mundo tiene 7 bloques; agua: 4"],
        source: "# sale: ..~~.\n# sale: .#~~.\n# sale: ##...\n# sale: el mundo tiene 7 bloques; agua: 4\n# un mundo de cubos en chico: cada bloque, por su SITIO -- un mapa cuya clave es un registro\nmod main \"un mundo de bloques\"\n\ntype Sitio\n    x: int\n    y: int\n\nfn pinta(mundo: {Sitio: text}, alto: int, ancho: int)\n    for y in range(alto)\n        let mut fila = \"\"\n        for x in range(ancho)\n            match get(mundo, Sitio { x: x, y: y })\n                Hay(b)\n                    fila = fila + b\n                NoHay\n                    fila = fila + \".\"\n        print(fila)\n\nfn main()\n    let mut mundo: {Sitio: text} = {}\n    for x in range(2)\n        put(mut mundo, Sitio { x: x, y: 2 }, \"#\")\n    put(mut mundo, Sitio { x: 1, y: 1 }, \"#\")\n    for y in range(2)\n        for x in range(2, 4)\n            put(mut mundo, Sitio { x: x, y: y }, \"~\")\n    pinta(mundo, 3, 5)\n    let mut agua = 0\n    for s in mundo\n        match get(mundo, s)\n            Hay(b)\n                if b == \"~\"\n                    agua = agua + 1\n            NoHay\n                print(\"?\")\n    print(\"el mundo tiene \", len(mundo), \" bloques; agua: \", agua)\n",
    },
];
